export const ADD_ALL_TO_BASKET = "ADD_ALL_TO_BASKET";
export const ADD_ACCESSORIES_TO_BASKET = "ADD_ACCESSORIES_TO_BASKET";
export const ADD_BEST_TO_BASKET = "ADD_BEST_TO_BASKET";

export const ADD_CONSOLES_TO_BASKET = "ADD_CONSOLES_TO_BASKET";
export const ADD_CONTROLLERS_TO_BASKET = "ADD_CONTROLLERS_TO_BASKET";
export const ADD_GAMES_TO_BASKET = "ADD_GAMES_TO_BASKET";
export const ADD_ONSALE_TO_BASKET = "ADD_ONSALE_TO_BASKET";
export const REMOVE_FROM_BASKET = "REMOVE_FROM_BASKET";
export const UPDATE_QUANTITY = "UPDATE_QUANTITY";
